### ISSUE TITLE
代码疑问

### ISSUE THREAD

**Issue by KIDxiaoyuan** [zjukg/MoMoK#2]
<img width="524" alt="P1" src="https://github.com/user-attachments/assets/e380817f-3f22-48de-9c2b-788901b3a52e">
<img width="719" alt="P2" src="https://github.com/user-attachments/assets/56156382-aa4f-40be-b68f-125b24eaa659">
<img width="518" alt="P3" src="https://github.com/user-attachments/assets/85d7dc1c-ea61-40dc-8c0d-63ef4a1c78f6">
图1中为MIEstimator最小化互信息传入的特征，其中EXPERT_OUTPUTS维度应该为[B,N,D],那么在def train estimator(self,embeddings):
strs,imgs,txts=embeddings
idx1,idx2=random.sample(range(self.num)，k=2)
str1,str2=strs[idx1,strs[idx2]
img1,img2=imgs[idx1],imgs[idx2]
txt1,txt2=txts[idx1],txts[idx2]中的STR1,STR2的维度为[N,D],这样的输入内容是否符合预期？根据文章的理解，也许传入特征应该是[N,D]更为合理，第一个维度应该是专家数量？
图2中的MOE专家网络返回值应该为3个值，但在图3 中只有两个，这样会导致运行报错，请问这样的设计是否合理？

**Comment by Zhang-Each** [comment]
同学你好，关于第一个问题，当前这个维度应该没有问题。关于第二个问题，这个是代码版本管理出了点问题，目前已改正，感谢指出。
