### ISSUE TITLE
pth文件下载地址

### ISSUE THREAD

**Issue by kernelLZ** [zjukg/MoMoK#3]
您好，请问pth文件从哪里下载呢？FileNotFoundError: [Errno 2] No such file or directory: 'datasets/MKG-Y/img_features.pth'

**Comment by liangwangshou** [comment]
这就是浙大？ 我笑了  开源都喜欢开的缺胳膊少腿是吧？

**Comment by Zhang-Each** [comment]
你好，后续我们会上传

**Comment by liangwangshou** [comment]
Ok,thanks. I am very sorry to say some bad words.I have already deleted them.
Good Luck for you!
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zjukg/MoMoK"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年8月12日(星期一) 下午5:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zjukg/MoMoK] pth文件下载地址 (Issue #3)





 
你好，后续我们会上传

**Comment by kernelLZ** [comment]
> 你好，后续我们会上传

非常感谢，请问大概什么时间会上传呢？很有趣的工作，期待上传。

**Comment by kernelLZ** [comment]
请问大概什么时间会上传呢？

**Comment by Zhang-Each** [comment]
> 请问大概什么时间会上传呢？

你好，该论文目前处于投稿阶段，需要等该论文被接收之后才会公开

**Comment by liangwangshou** [comment]
对于对比损失函数L_club有些疑问，论文说的是同一实体的不同视角作为对比，而源码里为什么是不同实体之间进行对比？







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zjukg/MoMoK"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年8月19日(星期一) 晚上10:28
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zjukg/MoMoK] pth文件下载地址 (Issue #3)





 
Closed #3 as completed.
