### ISSUE TITLE
对比loss关于对比对象和论文差异的问题

### ISSUE THREAD

**Issue by liangwangshou** [zjukg/MoMoK#4]
![image](https://github.com/user-attachments/assets/65a049f4-611a-4235-b822-9bd9a9da78dd)
对于对比损失函数L_club有些疑问，论文说的是同一实体的不同视角作为对比，而源码里为什么是不同实体之间进行对比？

**Comment by Zhang-Each** [comment]
你好，这里其实是一个in-batch负采样的过程，传入的x_smaples和y_samples也是来自于不同专家网络的两个输出，positive计算不同专家视角的分数，而negative通过在batch内进行负采样计算。

**Comment by liangwangshou** [comment]
您好，很感谢您的答复，您说的论文中的一致，我也明白，但是代码上有些疑问
光从代码的实现来看，这边的代码好像是让不同样本对应的专家(如：样本x的专家1和y的专家1作为正样本，而负样本则未样本x的专家1和样本y的专家2，同时附有下图，方便我更好表达我的疑问）

这是源代码，我已标记，方便您的观看







------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Yichi ***@***.***&gt;; 
发送时间: 2024年9月15日(星期天) 晚上6:09
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [zjukg/MoMoK] 对比loss关于对比对象和论文差异的问题 (Issue #4)














 
你好，这里其实是一个in-batch负采样的过程，传入的x_smaples和y_samples也是来自于不同专家网络的两个输出，positive计算不同专家视角的分数，而negative通过在batch内进行负采样计算。

**Comment by Zhang-Each** [comment]
你好，x_sample和y_sample只是变量名，不代表样本x和样本y，他们实际上是同一批实体的不同专家的输出结果
