### ISSUE TITLE
关于关系embeding的疑惑

### ISSUE THREAD

**Issue by liangwangshou** [zjukg/MoMoK#5]
您好，方便问一下该代码中，关系embedding的数量为什么要乘以2，是因为作为有向图么？那么我看训练集好像只训练了一个方向，但是验证和测试怎么两个方向都要呢？还是说该图谱作为一个无向图进行处理，那直接用一个对应关系的unique数量不就好了，为什么还要乘以2？

**Comment by Zhang-Each** [comment]
因为在训练的时候给每个关系生成了反向的关系-r，并且把原有的三元组h, r, t变成了两个三元组，一个还是h, r, t，另一个是t, -r, h，这样两个三元组都进行尾实体的预测，训练和测试都是这样，相当于正反两个方向都进行了，KGC模型中这种做法很常见

**Comment by liangwangshou** [comment]
您好，真诚的感谢您的回答。祝国庆快乐O(∩_∩)O



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Yichi ***@***.***&gt;; 
发送时间: 2024年10月2日(星期三) 晚上10:34
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [zjukg/MoMoK] 关于关系embeding的疑惑 (Issue #5)














 
因为在训练的时候给每个关系生成了反向的关系-r，并且把原有的三元组h, r, t变成了两个三元组，一个还是h, r, t，另一个是t, -r, h，这样两个三元组都进行尾实体的预测，训练和测试都是这样，相当于正反两个方向都进行了，KGC模型中这种做法很常见
